### PR TITLE
chat_watsapp

### PR DESCRIPTION
**Pull request by Vaidehi-dave**
this must receive sender's name, receiver's phone num and message to send a watsapp message combining the data... moving on...

### CODE REVIEW

**Comment by TazmanianDI** [comment]
@Vaidehi-dave What is this? This PR doesn't look like it has anything to do with the functionality in this repo. I'm inclined to just close this PR.

**Comment by Vaidehi-dave** [comment]
This was accepted long back, forked and worked upon by too many people
too... it is important!.. verified by system long back!... you seem to show
no authority to type this!

**Comment by TazmanianDI** [comment]
@Vaidehi-dave This PR has changes to one file that is in Java which is inconsistent will all the other code in this repo, doesn't appear to do any actual work other than output a few console.log statements and creates some sort of twilio message that doesn't appear to be sent. I don't see any code that integrates any of this functionality with the Watson Assistant Web Chat which is what this repo is for. Perhaps the PR is missing some updates or commits that are supposed to be here. If this is the case, then please create a new PR with the correct code. Until then, I am closing this PR.

> you seem to show no authority to type this!
I work for IBM and am an admin for this repo.

**Comment by Vaidehi-dave** [comment]
I am sorry

**Pull request closed without merging**
